-- ================================================================
-- Render PostgreSQL View Sync Migration #003
-- Date: 2025-11-03
-- Purpose: Deploy remaining 21 views that failed in migration #002
--
-- These views failed because migration #002 used manually-written SQL
-- with incorrect column names. This migration uses exact working SQL
-- extracted from local PostgreSQL database.
--
-- Missing Views (21 total):
--   auditorchanges, buybacksadj, dirnocname, issuedlatest,
--   lastmreturn, lookupadviser, stockcodes1000, webadv,
--   webadvships, webbuybacks, webcatmembers, webcattree,
--   webcountadvbyrole, webcurrlisted, webdelisted, webdirs,
--   webdirships, webholders3, webholdings3, webissues, weblistings
--
-- Critical Views:
--   - webholdings3: Required by orgdata.asp (currently failing 500)
--   - webadv, webissues, weblistings: Used by multiple routes
-- ================================================================

SET search_path TO enigma, ccass, public;

-- ================================================================
-- SECTION 1: VIEW DEFINITIONS (EXTRACTED FROM LOCAL POSTGRESQL)
-- ================================================================

                                                                                                                                       ?column?                                                                                                                                       
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CREATE OR REPLACE VIEW enigma.auditorchanges AS                                                                                                                                                                                                                                     +
  SELECT adviserships.company,                                                                                                                                                                                                                                                       +
     adviserships.adviser,                                                                                                                                                                                                                                                           +
     msdateacc(adviserships.adddate, adviserships.addacc) AS add,                                                                                                                                                                                                                    +
     msdateacc(adviserships.remdate, adviserships.remacc) AS rem,                                                                                                                                                                                                                    +
     COALESCE(adviserships.remdate, adviserships.adddate) AS sortdate,                                                                                                                                                                                                               +
     listedcoshkall.name AS coname,                                                                                                                                                                                                                                                  +
     organisations.name1 AS advname                                                                                                                                                                                                                                                  +
    FROM adviserships                                                                                                                                                                                                                                                                +
      JOIN listedcoshkall ON listedcoshkall.personid = adviserships.company                                                                                                                                                                                                          +
      JOIN organisations ON organisations.personid = adviserships.adviser                                                                                                                                                                                                            +
   WHERE adviserships.role = 0;;                                                                                                                                                                                                                                                     +
 
 CREATE OR REPLACE VIEW enigma.buybacksadj AS                                                                                                                                                                                                                                        +
  SELECT stockcodethen(c.issueid, c.effdate) AS stockcode,                                                                                                                                                                                                                           +
     c.issueid,                                                                                                                                                                                                                                                                      +
     c.effdate,                                                                                                                                                                                                                                                                      +
     c.exchid,                                                                                                                                                                                                                                                                       +
     COALESCE(b2.name, b1.name) AS exchname,                                                                                                                                                                                                                                         +
     (- c.shares)::double precision / getadjust(c.issueid, c.effdate) AS shares,                                                                                                                                                                                                     +
     c.value,                                                                                                                                                                                                                                                                        +
     cur.currency,                                                                                                                                                                                                                                                                   +
     concat(o.name1, ': ', st.typeshort) AS name                                                                                                                                                                                                                                     +
    FROM capchanges c                                                                                                                                                                                                                                                                +
      JOIN issue i ON i.id1 = c.issueid                                                                                                                                                                                                                                              +
      JOIN organisations o ON o.personid = i.issuer                                                                                                                                                                                                                                  +
      JOIN sectypes st ON i.typeid = st.typeid                                                                                                                                                                                                                                       +
      JOIN bbexch b1 ON c.exchid = b1.id                                                                                                                                                                                                                                             +
      LEFT JOIN currencies cur ON c.currency = cur.id                                                                                                                                                                                                                                +
      LEFT JOIN bbexch b2 ON b1.mapto = b2.id                                                                                                                                                                                                                                        +
   WHERE c.capchangetype = 1;;                                                                                                                                                                                                                                                       +
 
 CREATE OR REPLACE VIEW enigma.dirnocname AS                                                                                                                                                                                                                                         +
  SELECT DISTINCT d.company AS orgid,                                                                                                                                                                                                                                                +
     d.director,                                                                                                                                                                                                                                                                     +
     o.name1 AS orgname,                                                                                                                                                                                                                                                             +
     nameppl(p.name1, p.name2) AS pplname                                                                                                                                                                                                                                            +
    FROM directorships d                                                                                                                                                                                                                                                             +
      JOIN organisations o ON d.company = o.personid                                                                                                                                                                                                                                 +
      JOIN people p ON d.director = p.personid                                                                                                                                                                                                                                       +
      JOIN positions po ON d.positionid = po.positionid                                                                                                                                                                                                                              +
      JOIN listedcoshkever l ON d.company = l.issuer                                                                                                                                                                                                                                 +
   WHERE po.rank = 1 AND p.cname IS NULL                                                                                                                                                                                                                                             +
   ORDER BY o.name1, (nameppl(p.name1, p.name2));;                                                                                                                                                                                                                                   +
 
 CREATE OR REPLACE VIEW enigma.issuedlatest AS                                                                                                                                                                                                                                       +
  SELECT i.issueid,                                                                                                                                                                                                                                                                  +
     i.outstanding,                                                                                                                                                                                                                                                                  +
     i.atdate                                                                                                                                                                                                                                                                        +
    FROM issuedshares i                                                                                                                                                                                                                                                              +
      JOIN issuedlatestdate t ON i.issueid = t.issueid AND i.atdate = t.maxdate;;                                                                                                                                                                                                    +
 
 CREATE OR REPLACE VIEW enigma.lastmreturn AS                                                                                                                                                                                                                                        +
  SELECT stocklistings.stockcode,                                                                                                                                                                                                                                                    +
     organisations.name1 AS name,                                                                                                                                                                                                                                                    +
     sectypes.typeshort,                                                                                                                                                                                                                                                             +
     ( SELECT max(issuedshares.atdate) AS max                                                                                                                                                                                                                                        +
            FROM issuedshares                                                                                                                                                                                                                                                        +
           WHERE issuedshares.issueid = issue.id1) AS maxdate                                                                                                                                                                                                                        +
    FROM stocklistings                                                                                                                                                                                                                                                               +
      JOIN issue ON stocklistings.issueid = issue.id1                                                                                                                                                                                                                                +
      JOIN organisations ON issue.issuer = organisations.personid                                                                                                                                                                                                                    +
      JOIN sectypes ON issue.typeid = sectypes.typeid                                                                                                                                                                                                                                +
   WHERE (stocklistings.firsttradedate IS NULL OR stocklistings.firsttradedate <= CURRENT_DATE) AND (stocklistings.delistdate IS NULL OR stocklistings.delistdate > CURRENT_DATE) AND (stocklistings.stockexid = ANY (ARRAY[1, 20, 23])) AND (issue.typeid <> ALL (ARRAY[2, 40, 41]))+
   ORDER BY (( SELECT max(issuedshares.atdate) AS max                                                                                                                                                                                                                                +
            FROM issuedshares                                                                                                                                                                                                                                                        +
           WHERE issuedshares.issueid = issue.id1));;                                                                                                                                                                                                                                +
 
 CREATE OR REPLACE VIEW enigma.lookupadviser AS                                                                                                                                                                                                                                      +
  SELECT advisers.personid,                                                                                                                                                                                                                                                          +
     organisations.name1                                                                                                                                                                                                                                                             +
    FROM organisations                                                                                                                                                                                                                                                               +
      JOIN advisers ON organisations.personid = advisers.personid                                                                                                                                                                                                                    +
   ORDER BY organisations.name1;;                                                                                                                                                                                                                                                    +
 
 CREATE OR REPLACE VIEW enigma.stockcodes1000 AS                                                                                                                                                                                                                                     +
  SELECT stockcode                                                                                                                                                                                                                                                                   +
    FROM stocklistings                                                                                                                                                                                                                                                               +
   WHERE stockcode::text < '1000'::text AND (stockexid = ANY (ARRAY[1, 20, 22, 23, 38])) AND (delistdate IS NULL OR delistdate > CURRENT_TIMESTAMP)                                                                                                                                  +
   ORDER BY stockcode;;                                                                                                                                                                                                                                                              +
 
 CREATE OR REPLACE VIEW enigma.webadv AS                                                                                                                                                                                                                                             +
  SELECT org1.name1 AS org,                                                                                                                                                                                                                                                          +
     roles.role,                                                                                                                                                                                                                                                                     +
     roles.roleid,                                                                                                                                                                                                                                                                   +
     org2.name1 AS adv,                                                                                                                                                                                                                                                              +
     org1.personid AS orgid,                                                                                                                                                                                                                                                         +
     org2.personid AS advid,                                                                                                                                                                                                                                                         +
     adviserships.adddate,                                                                                                                                                                                                                                                           +
     adviserships.addacc,                                                                                                                                                                                                                                                            +
     adviserships.remdate,                                                                                                                                                                                                                                                           +
     adviserships.remacc,                                                                                                                                                                                                                                                            +
     roles.onetime                                                                                                                                                                                                                                                                   +
    FROM adviserships                                                                                                                                                                                                                                                                +
      JOIN organisations org1 ON org1.personid = adviserships.company                                                                                                                                                                                                                +
      JOIN organisations org2 ON org2.personid = adviserships.adviser                                                                                                                                                                                                                +
      JOIN roles ON roles.roleid = adviserships.role;;                                                                                                                                                                                                                               +
 
 CREATE OR REPLACE VIEW enigma.webadvships AS                                                                                                                                                                                                                                        +
  SELECT organisations.name1 AS org,                                                                                                                                                                                                                                                 +
     roles.role,                                                                                                                                                                                                                                                                     +
     roles.onetime,                                                                                                                                                                                                                                                                  +
     organisations.personid AS orgid,                                                                                                                                                                                                                                                +
     adviserships.adviser AS advid,                                                                                                                                                                                                                                                  +
     adviserships.adddate,                                                                                                                                                                                                                                                           +
     adviserships.addacc,                                                                                                                                                                                                                                                            +
     adviserships.remdate,                                                                                                                                                                                                                                                           +
     adviserships.remacc,                                                                                                                                                                                                                                                            +
     listedcoshk.issuer                                                                                                                                                                                                                                                              +
    FROM adviserships                                                                                                                                                                                                                                                                +
      JOIN organisations ON organisations.personid = adviserships.company                                                                                                                                                                                                            +
      JOIN roles ON roles.roleid = adviserships.role                                                                                                                                                                                                                                 +
      LEFT JOIN listedcoshk ON listedcoshk.issuer = adviserships.company;;                                                                                                                                                                                                           +
 
 CREATE OR REPLACE VIEW enigma.webbuybacks AS                                                                                                                                                                                                                                        +
  SELECT stockcodethen(c.issueid, c.effdate) AS stockcode,                                                                                                                                                                                                                           +
     c.issueid,                                                                                                                                                                                                                                                                      +
     c.effdate,                                                                                                                                                                                                                                                                      +
     c.exchid,                                                                                                                                                                                                                                                                       +
     COALESCE(b2.name, b1.name) AS exchname,                                                                                                                                                                                                                                         +
     - c.shares AS shares,                                                                                                                                                                                                                                                           +
     c.value,                                                                                                                                                                                                                                                                        +
     cur.currency,                                                                                                                                                                                                                                                                   +
     concat(o.name1, ': ', st.typeshort) AS name                                                                                                                                                                                                                                     +
    FROM capchanges c                                                                                                                                                                                                                                                                +
      JOIN issue i ON i.id1 = c.issueid                                                                                                                                                                                                                                              +
      JOIN organisations o ON o.personid = i.issuer                                                                                                                                                                                                                                  +
      JOIN sectypes st ON i.typeid = st.typeid                                                                                                                                                                                                                                       +
      JOIN bbexch b1 ON c.exchid = b1.id                                                                                                                                                                                                                                             +
      LEFT JOIN currencies cur ON c.currency = cur.id                                                                                                                                                                                                                                +
      LEFT JOIN bbexch b2 ON b1.mapto = b2.id                                                                                                                                                                                                                                        +
   WHERE c.capchangetype = 1;;                                                                                                                                                                                                                                                       +
 
 CREATE OR REPLACE VIEW enigma.webcatmembers AS                                                                                                                                                                                                                                      +
  SELECT organisations.personid,                                                                                                                                                                                                                                                     +
     organisations.name1,                                                                                                                                                                                                                                                            +
     classifications.category,                                                                                                                                                                                                                                                       +
     categories.name AS catname                                                                                                                                                                                                                                                      +
    FROM classifications                                                                                                                                                                                                                                                             +
      JOIN organisations ON organisations.personid = classifications.company                                                                                                                                                                                                         +
      JOIN categories ON categories.id = classifications.category                                                                                                                                                                                                                    +
   ORDER BY organisations.name1;;                                                                                                                                                                                                                                                    +
 
 CREATE OR REPLACE VIEW enigma.webcattree AS                                                                                                                                                                                                                                         +
  SELECT parent.name AS parentname,                                                                                                                                                                                                                                                  +
     child.name AS childname,                                                                                                                                                                                                                                                        +
     parent.id AS parentid,                                                                                                                                                                                                                                                          +
     child.id AS childid                                                                                                                                                                                                                                                             +
    FROM cattree                                                                                                                                                                                                                                                                     +
      JOIN categories parent ON parent.id = cattree.parentcat                                                                                                                                                                                                                        +
      JOIN categories child ON child.id = cattree.childcat;;                                                                                                                                                                                                                         +
 
 CREATE OR REPLACE VIEW enigma.webcountadvbyrole AS                                                                                                                                                                                                                                  +
  SELECT roles.roleid,                                                                                                                                                                                                                                                               +
     roles.rolelong AS role,                                                                                                                                                                                                                                                         +
     roles.onetime,                                                                                                                                                                                                                                                                  +
     count(adviserships.role) AS countofrole                                                                                                                                                                                                                                         +
    FROM adviserships                                                                                                                                                                                                                                                                +
      JOIN roles ON roles.roleid = adviserships.role                                                                                                                                                                                                                                 +
      JOIN listedcoshk ON listedcoshk.issuer = adviserships.company                                                                                                                                                                                                                  +
   WHERE adviserships.remdate IS NULL OR adviserships.remdate > CURRENT_TIMESTAMP                                                                                                                                                                                                    +
   GROUP BY roles.roleid, roles.rolelong, roles.onetime                                                                                                                                                                                                                              +
   ORDER BY roles.rolelong;;                                                                                                                                                                                                                                                         +
 
 CREATE OR REPLACE VIEW enigma.webcurrlisted AS                                                                                                                                                                                                                                      +
  SELECT stocklistings.stockcode,                                                                                                                                                                                                                                                    +
     organisations.name1,                                                                                                                                                                                                                                                            +
     sectypes.typeshort AS type,                                                                                                                                                                                                                                                     +
     organisations.personid,                                                                                                                                                                                                                                                         +
     stocklistings.stockexid,                                                                                                                                                                                                                                                        +
     "left"(sectypes.typeshort::text, 1) AS type1,                                                                                                                                                                                                                                   +
     stocklistings.firsttradedate,                                                                                                                                                                                                                                                   +
     organisations.domicile                                                                                                                                                                                                                                                          +
    FROM stocklistings                                                                                                                                                                                                                                                               +
      JOIN issue ON issue.id1 = stocklistings.issueid                                                                                                                                                                                                                                +
      JOIN organisations ON organisations.personid = issue.issuer                                                                                                                                                                                                                    +
      JOIN sectypes ON issue.typeid = sectypes.typeid                                                                                                                                                                                                                                +
      JOIN listings ON listings.stockexid = stocklistings.stockexid                                                                                                                                                                                                                  +
   WHERE (stocklistings.stockexid = ANY (ARRAY[1, 20, 22, 23, 38])) AND (stocklistings.firsttradedate IS NULL OR stocklistings.firsttradedate <= CURRENT_TIMESTAMP) AND (stocklistings.delistdate IS NULL OR stocklistings.delistdate > CURRENT_TIMESTAMP)                           +
   ORDER BY organisations.name1, sectypes.typeshort;;                                                                                                                                                                                                                                +
 
 CREATE OR REPLACE VIEW enigma.webdelisted AS                                                                                                                                                                                                                                        +
  SELECT stocklistings.stockcode,                                                                                                                                                                                                                                                    +
     stocklistings.issueid,                                                                                                                                                                                                                                                          +
     organisations.name1,                                                                                                                                                                                                                                                            +
     organisations.domicile,                                                                                                                                                                                                                                                         +
     sectypes.typeshort AS type,                                                                                                                                                                                                                                                     +
     stocklistings.firsttradedate,                                                                                                                                                                                                                                                   +
     stocklistings.finaltradedate,                                                                                                                                                                                                                                                   +
     stocklistings.delistdate,                                                                                                                                                                                                                                                       +
     organisations.personid,                                                                                                                                                                                                                                                         +
     stocklistings.stockexid,                                                                                                                                                                                                                                                        +
     dlreasons.reason,                                                                                                                                                                                                                                                               +
         CASE                                                                                                                                                                                                                                                                        +
             WHEN stocklistings.firsttradedate IS NULL OR stocklistings.finaltradedate IS NULL THEN NULL::numeric                                                                                                                                                                    +
             ELSE (stocklistings.finaltradedate - stocklistings.firsttradedate + 1)::numeric / 365.2425                                                                                                                                                                              +
         END AS tradelife                                                                                                                                                                                                                                                            +
    FROM stocklistings                                                                                                                                                                                                                                                               +
      JOIN issue ON stocklistings.issueid = issue.id1                                                                                                                                                                                                                                +
      JOIN organisations ON issue.issuer = organisations.personid                                                                                                                                                                                                                    +
      JOIN sectypes ON issue.typeid = sectypes.typeid                                                                                                                                                                                                                                +
      JOIN listings ON stocklistings.stockexid = listings.stockexid                                                                                                                                                                                                                  +
      LEFT JOIN dlreasons ON stocklistings.reasonid = dlreasons.reasonid                                                                                                                                                                                                             +
   WHERE stocklistings.delistdate <= CURRENT_TIMESTAMP AND (stocklistings.stockexid = ANY (ARRAY[1, 20, 22, 23, 38]));;                                                                                                                                                              +
 
 CREATE OR REPLACE VIEW enigma.webdirs AS                                                                                                                                                                                                                                            +
  SELECT concat(people.name1, ', ', COALESCE(people.name2, ''::character varying)) AS dir,                                                                                                                                                                                           +
     positions.posshort AS "position",                                                                                                                                                                                                                                               +
     positions.rank,                                                                                                                                                                                                                                                                 +
     positions.poslong,                                                                                                                                                                                                                                                              +
     directorships.director AS dirid,                                                                                                                                                                                                                                                +
     directorships.company AS orgid,                                                                                                                                                                                                                                                 +
     directorships.apptdate,                                                                                                                                                                                                                                                         +
     directorships.resdate,                                                                                                                                                                                                                                                          +
     directorships.apptacc,                                                                                                                                                                                                                                                          +
     directorships.resacc,                                                                                                                                                                                                                                                           +
     people.yob                                                                                                                                                                                                                                                                      +
    FROM directorships                                                                                                                                                                                                                                                               +
      JOIN people ON people.personid = directorships.director                                                                                                                                                                                                                        +
      JOIN positions ON positions.positionid = directorships.positionid;;                                                                                                                                                                                                            +
 
 CREATE OR REPLACE VIEW enigma.webdirships AS                                                                                                                                                                                                                                        +
  SELECT positions.posshort AS "position",                                                                                                                                                                                                                                           +
     positions.rank,                                                                                                                                                                                                                                                                 +
     positions.poslong,                                                                                                                                                                                                                                                              +
     organisations.name1 AS org,                                                                                                                                                                                                                                                     +
     directorships.director AS dirid,                                                                                                                                                                                                                                                +
     organisations.personid AS orgid,                                                                                                                                                                                                                                                +
     directorships.apptdate,                                                                                                                                                                                                                                                         +
     directorships.resdate,                                                                                                                                                                                                                                                          +
     directorships.apptacc,                                                                                                                                                                                                                                                          +
     directorships.resacc,                                                                                                                                                                                                                                                           +
     listedcoshkall.stockexid                                                                                                                                                                                                                                                        +
    FROM directorships                                                                                                                                                                                                                                                               +
      JOIN organisations ON organisations.personid = directorships.company                                                                                                                                                                                                           +
      JOIN positions ON positions.positionid = directorships.positionid                                                                                                                                                                                                              +
      LEFT JOIN listedcoshkall ON organisations.personid = listedcoshkall.personid;;                                                                                                                                                                                                 +
 
 CREATE OR REPLACE VIEW enigma.webholders3 AS                                                                                                                                                                                                                                        +
  SELECT sh.issueid AS issue,                                                                                                                                                                                                                                                        +
     sh.holderid AS personid,                                                                                                                                                                                                                                                        +
     sh.atdate AS holdingdate,                                                                                                                                                                                                                                                       +
     sh.shares,                                                                                                                                                                                                                                                                      +
     sh.stake,                                                                                                                                                                                                                                                                       +
         CASE                                                                                                                                                                                                                                                                        +
             WHEN pe.personid IS NOT NULL THEN 'P'::text                                                                                                                                                                                                                             +
             WHEN o.personid IS NOT NULL THEN 'O'::text                                                                                                                                                                                                                              +
             ELSE NULL::text                                                                                                                                                                                                                                                         +
         END AS persontype,                                                                                                                                                                                                                                                          +
     COALESCE(                                                                                                                                                                                                                                                                       +
         CASE                                                                                                                                                                                                                                                                        +
             WHEN pe.personid IS NOT NULL THEN pe.name1::text || COALESCE(', '::text || pe.name2::text, ''::text)                                                                                                                                                                    +
             ELSE NULL::text                                                                                                                                                                                                                                                         +
         END, o.name1::text) AS name,                                                                                                                                                                                                                                                +
     o.orgtype,                                                                                                                                                                                                                                                                      +
     o.domicile,                                                                                                                                                                                                                                                                     +
     d.a2,                                                                                                                                                                                                                                                                           +
     d.friendly,                                                                                                                                                                                                                                                                     +
     o.incdate,                                                                                                                                                                                                                                                                      +
     o.incacc,                                                                                                                                                                                                                                                                       +
     i.typeid AS sectype,                                                                                                                                                                                                                                                            +
     st.typeshort,                                                                                                                                                                                                                                                                   +
     st.typelong                                                                                                                                                                                                                                                                     +
    FROM sholdings sh                                                                                                                                                                                                                                                                +
      LEFT JOIN people pe ON sh.holderid = pe.personid                                                                                                                                                                                                                               +
      LEFT JOIN organisations o ON sh.holderid = o.personid                                                                                                                                                                                                                          +
      LEFT JOIN domiciles d ON o.domicile = d.id                                                                                                                                                                                                                                     +
      JOIN issue i ON sh.issueid = i.id1                                                                                                                                                                                                                                             +
      LEFT JOIN sectypes st ON i.typeid = st.typeid                                                                                                                                                                                                                                  +
   WHERE sh.heldas = 0;;                                                                                                                                                                                                                                                             +
 
 CREATE OR REPLACE VIEW enigma.webholdings3 AS                                                                                                                                                                                                                                       +
  SELECT sh.holderid AS personid,                                                                                                                                                                                                                                                    +
     sh.issueid AS issue,                                                                                                                                                                                                                                                            +
     sh.atdate AS holdingdate,                                                                                                                                                                                                                                                       +
     sh.shares,                                                                                                                                                                                                                                                                      +
     sh.stake,                                                                                                                                                                                                                                                                       +
     i.issuer,                                                                                                                                                                                                                                                                       +
     i.typeid AS sectype,                                                                                                                                                                                                                                                            +
     st.typeshort,                                                                                                                                                                                                                                                                   +
     st.typelong,                                                                                                                                                                                                                                                                    +
     o.name1 AS name,                                                                                                                                                                                                                                                                +
     o.orgtype,                                                                                                                                                                                                                                                                      +
     d.a2,                                                                                                                                                                                                                                                                           +
     d.friendly,                                                                                                                                                                                                                                                                     +
     o.incdate,                                                                                                                                                                                                                                                                      +
     o.incacc                                                                                                                                                                                                                                                                        +
    FROM sholdings sh                                                                                                                                                                                                                                                                +
      JOIN issue i ON sh.issueid = i.id1                                                                                                                                                                                                                                             +
      JOIN organisations o ON i.issuer = o.personid                                                                                                                                                                                                                                  +
      LEFT JOIN sectypes st ON i.typeid = st.typeid                                                                                                                                                                                                                                  +
      LEFT JOIN domiciles d ON o.domicile = d.id                                                                                                                                                                                                                                     +
   WHERE sh.heldas = 0;;                                                                                                                                                                                                                                                             +
 
 CREATE OR REPLACE VIEW enigma.webissues AS                                                                                                                                                                                                                                          +
  SELECT issue.id1,                                                                                                                                                                                                                                                                  +
     sectypes.typeshort AS sectype,                                                                                                                                                                                                                                                  +
     organisations.name1 AS issuer,                                                                                                                                                                                                                                                  +
     organisations.personid AS person                                                                                                                                                                                                                                                +
    FROM issue                                                                                                                                                                                                                                                                       +
      JOIN organisations ON organisations.personid = issue.issuer                                                                                                                                                                                                                    +
      JOIN sectypes ON issue.typeid = sectypes.typeid;;                                                                                                                                                                                                                              +
 
 CREATE OR REPLACE VIEW enigma.weblistings AS                                                                                                                                                                                                                                        +
  SELECT stocklistings.stockcode,                                                                                                                                                                                                                                                    +
     sectypes.typeshort AS sectype,                                                                                                                                                                                                                                                  +
     organisations.name1 AS org,                                                                                                                                                                                                                                                     +
     stocklistings.delistdate,                                                                                                                                                                                                                                                       +
     organisations.personid AS orgid,                                                                                                                                                                                                                                                +
     stocklistings.firsttradedate,                                                                                                                                                                                                                                                   +
     stocklistings.finaltradedate,                                                                                                                                                                                                                                                   +
     listings.shortname,                                                                                                                                                                                                                                                             +
     stocklistings.issueid,                                                                                                                                                                                                                                                          +
     listings.stockexid,                                                                                                                                                                                                                                                             +
     dlreasons.reason                                                                                                                                                                                                                                                                +
    FROM stocklistings                                                                                                                                                                                                                                                               +
      JOIN issue ON stocklistings.issueid = issue.id1                                                                                                                                                                                                                                +
      JOIN organisations ON issue.issuer = organisations.personid                                                                                                                                                                                                                    +
      JOIN sectypes ON issue.typeid = sectypes.typeid                                                                                                                                                                                                                                +
      JOIN listings ON stocklistings.stockexid = listings.stockexid                                                                                                                                                                                                                  +
      LEFT JOIN dlreasons ON stocklistings.reasonid = dlreasons.reasonid                                                                                                                                                                                                             +
   WHERE listings.stockexid = ANY (ARRAY[1, 20, 22, 23, 38, 71])                                                                                                                                                                                                                     +
   ORDER BY sectypes.typeshort, stocklistings.firsttradedate;;                                                                                                                                                                                                                       +
 
(21 rows)


-- ================================================================
-- SECTION 2: VERIFICATION
-- ================================================================

-- Count views in enigma schema (should be 46 after this migration)
DO $$
DECLARE
    view_count INTEGER;
BEGIN
    SELECT COUNT(*) INTO view_count
    FROM pg_views
    WHERE schemaname = 'enigma';

    RAISE NOTICE 'Enigma views: % (expected: 46)', view_count;
    
    IF view_count < 46 THEN
        RAISE WARNING 'View count is less than expected (46)';
    ELSE
        RAISE NOTICE '✓ All views deployed successfully';
    END IF;
END $$;

-- Test critical webholdings3 view
DO $$
DECLARE
    test_count INTEGER;
BEGIN
    SELECT COUNT(*) INTO test_count
    FROM information_schema.views
    WHERE table_schema = 'enigma' AND table_name = 'webholdings3';

    IF test_count = 1 THEN
        RAISE NOTICE '✓ webholdings3 view exists';
    ELSE
        RAISE WARNING '✗ webholdings3 view missing';
    END IF;
END $$;

-- Test webholders3 view
DO $$
DECLARE
    test_count INTEGER;
BEGIN
    SELECT COUNT(*) INTO test_count
    FROM information_schema.views
    WHERE table_schema = 'enigma' AND table_name = 'webholders3';

    IF test_count = 1 THEN
        RAISE NOTICE '✓ webholders3 view exists';
    ELSE
        RAISE WARNING '✗ webholders3 view missing';
    END IF;
END $$;

-- ================================================================
-- END OF MIGRATION
-- ================================================================
